### ISSUE TITLE
Replace PHP session superglobal with use of cookies

### ISSUE THREAD

**Issue by binarygary** [FixUpFox/Digital-Garden#1]
The `$_SESSION` superglobal can be problematic and either prevent full page caching OR work incorrectly if full page caching is in place. Most common WP hosts are leveraging full page caching for logged out users. 

This issue is to refactor `includes/class-digital-garden-frontend.php` to store note visits for the purpose of creating breadcrumbs in cookie/local storage.

Comments? Objections? Concerns?

**Comment by davidwolfpaw** [comment]
I don't have objections or concerns. As far as comment, do you have a suggestion on how best to do this? I haven't given it much thought yet.

**Comment by binarygary** [comment]
I'm going to try using local storage. 
It will be json with an array of object with title and url. I don't think we will need the id?

I'll open a PR to test against and we can see how it works. If you're happy with it we can move forward or revise.

One side effect is the recently viewed array will be _more_ persistent given the way PHP [handles sessions](https://stackoverflow.com/questions/1516266/how-long-will-my-session-last#answer-1516338).
